### ISSUE TITLE
Publish latest to pypi

### ISSUE THREAD

**Issue by caffodian** [vtemian/buffpy#12]
Hi,

Could we please get master published to pypi?  Some breaking bugs such as #7 still exist in the pypi version.

We may also want to consider changing the version scheme as presently it complains with a PEP440 error.  

Please let me know if I can help in any way.  

Thanks!
##

**Comment by TomAnthony** [comment]
+1 Would be good to get this fixed - just tripped me up.

**Comment by pavelsterba** [comment]
[bufferapp](https://pypi.python.org/pypi/bufferapp/0.2.0) seems like solution for this
