### ISSUE TITLE
AttributeError: 'Profile' object has no attribute 'id'

### ISSUE THREAD

**Issue by ishandutta2007** [vtemian/buffpy#17]
Just updated and ran `python examples/profiles.py `

**Comment by ishandutta2007** [comment]
> Traceback (most recent call last):
>   File "examples/profiles.py", line 24, in <module>
>     pp(profile.schedules)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/buffpy/models/profile.py", line 32, in schedules
>     url = PATHS["GET_SCHEDULES"].format(self.id)
> AttributeError: 'Profile' object has no attribute 'id'

**Comment by fernand0** [comment]
Hello,

I've solved it substituting self.id by self['id'] but I'm not sure if it is the correct way.

**Comment by ishandutta2007** [comment]
@fernand0 Yes exactly. For all examples I had to do that.Not sure why no one has updated it

**Comment by fernand0** [comment]
Hello @ishandutta2007, I tried it but I was not able to use it (not sure about how to include the image). I found another module (https://github.com/LevPasha/Instagram-API-python ) and I'm using it in my own module: https://github.com/fernand0/scripts/blob/master/moduleInstagram.py

**Comment by ishandutta2007** [comment]
Including image is straight forward. just put a link to photo here.. it should be a cdn link. https://github.com/vtemian/buffpy/blob/6c9236fd3b6a8f9e2d70dbf1bc01529242b73075/buffpy/tests/test_updates_manager.py#L132

I am looking for options like setting location or tagging a user

**Comment by ishandutta2007** [comment]
In `InstagramAPI` you don't use Buffer or alike to schedule ?

**Comment by ishandutta2007** [comment]
I checked your script, basically you are running your own scheduler. right?
you can check https://github.com/socialbotspy/BufferPy , we have got scheduling working via buffer using the current lib. We are just waiting on the Location field to make experience more complete.
For other APIs I use https://github.com/instagrambot.

**Comment by fernand0** [comment]
> Including image is straight forward. just put a link to 'photo' here.. it should be a cdn link.
> 
> https://github.com/vtemian/buffpy/blob/6c9236fd3b6a8f9e2d70dbf1bc01529242b73075/buffpy/tests/test_updates_manager.py#L132
> 
> I am looking for options like setting location or tagging a user

Yes, it is but I wanted to upload the image directly, not to put it somewhere in order to upload it to Instagram.

**Comment by fernand0** [comment]
> I checked your script, basically you are running your own scheduler. right?
> you can check https://github.com/socialbotspy/BufferPy , we have got scheduling working via buffer using the current library. We are just waiting on the Location field to make experience more complete.
> For other APIs I use https://github.com/instagrambot.

Yes I'm using cron to schedule posts. I'll check your links, thanks!

**Comment by vtemian** [comment]
@fernand0 @ishandutta2007 sorry for the late reply.
This issue should be fixed, I just didn't release the package on pypi.

**Comment by ishandutta2007** [comment]
@vtemian I made the necessary change, I am using your API but buffer don't seem to have location for instagram posts in their API which they have in their web version. Do you know of any work around ?

**Comment by ishandutta2007** [comment]
@vtemian  we were discussing scripts from examples folder, nothing to do with publishing to pypi. But after some modification of how you were traversing the recived object now it works fine. Basic request response is fine. Btw I am working cloning your repo. I didn't even know pypi

**Comment by vtemian** [comment]
@ishandutta2007 sadly I don't know any fix for your problem.
Regarding the publishing, I was referring that the scripts from examples are working with the current version from `master`. If you installed the package via git, directly from `master`, they should work. Otherwise, if you installed it via pypi, then you need to make the changes you mentioned.

**Comment by ishandutta2007** [comment]
> If you installed the package via git, directly from master,  they should work.

Well I had to change all `profile.updates` to `profile['updates']` and so on for other objects as well.

**Comment by ishandutta2007** [comment]
> sadly I don't know any fix for your problem.

well one thing I am trying is to call that API via ajax which the web version is calling, it's not the exact `updates.new()` api as it has other attributes exposed
