### ISSUE TITLE
GeoLocation not supported via API

### ISSUE THREAD

**Issue by ishandutta2007** [vtemian/buffpy#21]

**Comment by ishandutta2007** [comment]
Solved it here https://github.com/vtemian/buffpy/pull/22

**Comment by ishandutta2007** [comment]
@vtemian Now that Buffer.com is sunsetting their API, any plans of unofficial API ?

**Comment by vtemian** [comment]
Hmm....sadly no. I'll do only small maintenance tasks for it and mainly that's it.
If you want to fork it and continue working on it, please do.
